apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-shared-jupyter
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  awsElasticBlockStore: 
    fsType: "ext4" 
    volumeID: "vol-jupyter-shared" 
