apiVersion: apps/v1
kind: Deployment
metadata:
  name: xbs-dpmnt
  labels:
    app: xbs-app-dpmnt
    type: front-end-dpmnt
spec:
  template:
    metadata:
      name: xbs-pod
      labels:
        app: xbs-app-pod
        type: front-end-dpmnt
    spec:
      containers:
      - name: xbs-container
        image: ppnp/simple_html
  replicas: 3
  selector:
    matchLabels:
      type: front-end-dpmnt
---
# Type of Service: NodePort
apiVersion: v1
kind: Service
metadata:
  name: xbs-nodeport-svc
  labels:
    type: front-end-dpmnt
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 80
    nodePort: 30080
  selector:
    type: front-end-dpmnt
