apiVersion: v1
kind: ReplicationController
metadata:
  name: xbs-rc
  labels:
    app: xbs-app-rc
    type: front-end-rc
spec:
  template:
    metadata:
      name: xbs-pod
      labels:
        app: xbs-app-pod
        type: front-end-pod
    spec:
      containers:
      - name: nginx-container
        image: nginx
  replicas: 3