apiVersion: apps/v1
kind: Deployment
metadata:
  name: xbs-dpmnt
  labels:
    app: xbs-app-dpmnt
    type: front-end-dpmnt
spec:
  template:
    metadata:
      name: xbs-pod
      labels:
        app: xbs-app-pod
        type: front-end-dpmnt
    spec:
      containers:
      - name: xbs-container
        image: ppnp/simple_html
  replicas: 3
  selector:
    matchLabels:
      type: front-end-dpmnt
---
# Type of Service: Cluster-IP
kind: Service
apiVersion: v1
metadata:
  name: xbs-service
spec:
  selector:
    type: front-end-dpmnt
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 80
