apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-shared-jupyter
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
  storageClassName: gp2
